name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Kotlin Linter
      run: ./gradlew ktlintCheck
    - name: Run Android Linter
      run: ./gradlew lint
    - name: Build
      run: ./gradlew build
