name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: burrunan/gradle-cache-action@v1
      name: Test
      with:
        job-id: jdk8
        arguments: testDebug
        properties: |
          kotlin.parallel.tasks.in.project=true
    - name: Upload Test Reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: 'app/build/reports/tests/'
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: app/build/test-results/**/*.xml
    - uses: burrunan/gradle-cache-action@v1
      name: Run Kotlin Linter
      with:
        job-id: jdk8
        arguments: ktlintCheck
        properties: |
          kotlin.parallel.tasks.in.project=true
    - uses: burrunan/gradle-cache-action@v1
      name: Run Android Linter
      with:
        job-id: jdk8
        arguments: lintDebug
        properties: |
          kotlin.parallel.tasks.in.project=true
    - name: Upload Lint Reports
      uses: actions/upload-artifact@v2
      with:
        name: lint-reports
        path: 'app/build/reports/lint-results-*'
    - name: Publish Android Lint
      uses: yutailang0119/action-android-lint@v2.0.0
      with:
        report-path: 'app/build/reports/lint-results-*.xml'
    - uses: burrunan/gradle-cache-action@v1
      name: Assemble
      with:
        job-id: jdk8
        arguments: assembleDebug
        properties: |
          kotlin.parallel.tasks.in.project=true


  androidtest:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest --info