name: Scan with Detekt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
     - cron: '29 12 * * 1'

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: detekt
      uses: natiginfo/action-detekt-all@1.19.0
