name: Release

on:
  release:
    type: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: ./gradlew testRelease
    - name: Upload Test Reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: 'app/build/reports/tests/'
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: app/build/test-results/**/*.xml
    - name: Run Kotlin Linter
      run: ./gradlew ktlintCheck
    - name: Run Android Linter
      run: ./gradlew lintRelease
    - name: Upload Lint Reports
      uses: actions/upload-artifact@v2
      with:
        name: lint-reports
        path: 'app/build/reports/lint-results-*'
    - name: Publish Android Lint
      uses: yutailang0119/action-android-lint@v2.0.0
      with:
        report-path: 'app/build/reports/lint-results-*.xml'
    - name: Assemble
      run: ./gradlew assembleRelease

    - name: Sign release
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload Released AAB
      uses: actions/upload-artifact@v2
      with:
        name: Signed app bundle
        path: ${{steps.sign_app.outputs.signedReleaseFile}}


